#Creating Datanode for hadoop cluster 
#

apiVersion: apps/v1

kind: DaemonSet

metadata: 
   name: datanode
   namespace: {{ .Values.namespace }}

spec:
    selector:
            matchLabels:
                    name: datanode
    template:
            metadata:
                    name: datanode
                    labels:
                            name: datanode
            spec:
                    nodeSelector:
                            {{ .Values.keyworker }}: {{ .Values.valueworker }}
                    volumes:
                    - name: task-pv-storage
                      persistentVolumeClaim:
                           claimName: mypvc
                    containers:        
                    - name: "datanode-cont"
                      image: pranay1603/datanode:v2
                      volumeMounts:
                      - mountPath: "/data"
                        name: task-pv-storage
                      readinessProbe:
                                initialDelaySeconds: 1
                                periodSeconds: 5
                                timeoutSeconds: 1
                                successThreshold: 1
                                failureThreshold: 1
                                tcpSocket:
                                    host:
                                    port: 50010

                      env:
                      - name: IP
                        value: {{ .Values.IP }}
                      # master is open at fixed port 31000
                      - name: PORT
                        value: "31000" 







