# creating a namespace for our infrastrucre 
#
#apiVersion: v1

#kind: Namespace

#metadata:
# name: {{ .values.namespace }}


-------------------------------------------------------
# Creating service for exposing master node 
#
apiVersion: v1

kind: Service

metadata:
        name: master-service
        #namespace: {{ .values.namespace }} 

spec:
   selector:
       name: master
   type: NodePort
   ports:
   - protocol: TCP
     port: 9001   
     nodePort: 31000     
