# Creating service for exposing master node #
apiVersion: v1

kind: Service

metadata:
        name: master-service
        namespace: {{ .Values.namespace }}


spec:
   selector:
       name: master
   type: NodePort
   ports:
   - name: master-port        
     protocol: TCP
     port: 9001   
     nodePort: 31000
   - name: webui
     protocol: TCP
     port: 50070
     nodePort: 32000     
